### ISSUE TITLE
prematch argument

### ISSUE THREAD

**Issue by d2sys** [bshall/knn-vc#16]
Hi,

Thank you for this great repo!

In the readme file you mention that prematch option applies prematching the features. But in the [code](https://github.com/bshall/knn-vc/blob/master/prematch_dataset.py#L130) I see that prematch saves all the source features AS-IS without matching them one to each other. Can you please elaborate, I think I'm missing something.

Thanks

**Comment by RF5** [comment]
Hi @d2sys 

Thanks for catching that! Sorry it seems somewhere during the code cleanup for production some things got switched (should be `not args.prematch`). I see there was also another typo for `args.fast_l2` -- I just committed a fix for both of those now, it should operate as expected now :). 

Thanks for catching the bug!

**Comment by d2sys** [comment]
Thanks!
