### ISSUE TITLE
How to plug-in new finetuned HiFiGAN? 

### ISSUE THREAD

**Issue by youssefabdelm** [bshall/knn-vc#34]
Hey! I know you wrote about this here: https://github.com/bshall/knn-vc/issues/23

I think I'm going to go ahead and try those steps now

However, I did find this 48K HiFiGAN model someone trained (seemingly I could be wrong): https://github.com/vtuber-plan/hifi-gan/releases/tag/v0.3.1

Is it possible to plug that .pt checkpoint into knn-vc as is or does it need to still be trained further?

**Comment by EmreOzkose** [comment]
I think your mentioned vocoder model is trained with mel-spectrograms, but this repo uses wavLM as audio encoder. Hence I think you should train again.
