### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by dillfrescott** [bshall/knn-vc#36]
Do you think you could make this 48000hz compatible?

**Comment by RF5** [comment]
Hi @dillfrescott , we probably could, perhaps with apply a speech enhancment model on top of knnvc (there are several, such as Nuwave2). Unfortunately I don't have the time bandwidth to do this, but I encourage you to try, and if it works nicely, please let us know!

**Comment by dillfrescott** [comment]
Okay!
