### ISSUE TITLE
Using better neural vocoder GAN (BIGVGAN, RVQGAN ...)

### ISSUE THREAD

**Issue by tcourat** [bshall/knn-vc#38]
Anyone tried to use a different, more recent (and supposedly) better vocoder ?

HiFI-Gan is already a bit old and better options appeared like [BIGVGAN](https://github.com/NVIDIA/BigVGAN) and maybe [RVQGAN](https://github.com/descriptinc/descript-audio-codec).

**Comment by RF5** [comment]
Hi @tcourat , there have been a few people over the last year or so who have raised the idea, but I don't think anyone has released any BIGVGAN/RVQGAN vocoders publically. I unfortunately don't have the time at the moment to make them myselves, but if you are interested, please feel free to share it and I can add it to the repo. All the best!
