### ISSUE TITLE
Cannot download model.

### ISSUE THREAD

**Issue by sai4july** [bshall/knn-vc#42]
I try to download model from https://github.com/bshall/knn-vc/releases/, but it shows that i am not authorized.
![Xnip2024-08-18_14-31-48](https://github.com/user-attachments/assets/99c8e5d7-53aa-4f2b-beef-4c0ee1094bd6)

**Comment by RF5** [comment]
Hi @sai4july , this is very strange.... We can still download it, and no-one else has had issues with the download before. Could using a VPN to a different location perhaps fix the problem? We don't have a way of reproducing it...

**Comment by sai4july** [comment]
Hi @RF5. Thank you for your reply. I have tried using a VPN and asked two of my friends to help me download the model, but we still failed. I am wondering if you can provide the code to convert the model from https://huggingface.co/microsoft/wavlm-large/tree/main to the model in your repository.

**Comment by sai4july** [comment]
> Hi @sai4july , this is very strange.... We can still download it, and no-one else has had issues with the download before. Could using a VPN to a different location perhaps fix the problem? We don't have a way of reproducing it...

Hi @RF5. We can start the download, but it fails midway. Have you successfully downloaded the entire model？

**Comment by RF5** [comment]
I have been able to download it fully... very strange. The other places you can download the exact same model is [here](https://github.com/microsoft/unilm/tree/master/wavlm) -- maybe that can work as an alternative.

**Comment by sai4july** [comment]
> I have been able to download it fully... very strange. The other places you can download the exact same model is [here](https://github.com/microsoft/unilm/tree/master/wavlm) -- maybe that can work as an alternative.

Thank you, I have successfully downloaded the model from the new link.
