### ISSUE TITLE
torchaudio version

### ISSUE THREAD

**Issue by Blakey-Gavin** [bshall/knn-vc#7]
Hi, When I execute the program according to the Quickstart in README.md, the following error is reported:

AttributeError: module 'torchaudio.functional' has no attribute 'loudness'

I guess it is not supported in the torchaudio version I am using, the version I am using is: pytorch==1.12.1 torchaudio==0.12.1. 

Can you tell me which version you are using? Thanks.

**Comment by RF5** [comment]
Hi, sorry for the confusion. The code requires pytorch>=2.0 to work. I updated the readme now to state this.

The older pytorch v1.12 will not work, but if you update to pytorch and torchaudio to >=2.0, then it should work correctly.

Hope that helps!

**Comment by Blakey-Gavin** [comment]
Yes, I've got it working as you suggested. Thanks a lot for your answer.
