### ISSUE TITLE
Discriminator checkpoint

### ISSUE THREAD

**Issue by hippotabek** [bshall/knn-vc#8]
Hey!  Thank you for sharing your work, I really like ur idea!

I am trying to finetune vocoder for a specific voice to see whether it would improve voice matching, because voice doesn't match well at zero-shot setting. Could you please share discriminator weights of vocoder with prematching?

**Comment by RF5** [comment]
As mentioned in the [readme](https://github.com/bshall/knn-vc#checkpoints), we provide both prematched and unmatched discriminator and optimizer weights under the [releases tab](https://github.com/bshall/knn-vc/releases/tag/v0.1). 

Under the release you can see download links for both discriminator checkpoints and optimizer states (e.g. [https://github.com/bshall/knn-vc/releases/download/v0.1/do_02500000.pt](https://github.com/bshall/knn-vc/releases/download/v0.1/do_02500000.pt)). These should work well for fine-tuning with :)
